### ISSUE TITLE
Failure to build on MacOSX

### ISSUE THREAD

**Issue by abradle** [nitram509/jbrotli#1]
I pulled the git repo
Ran:
cd jbrotli/jbrotli-native
mvn package -X

First issue was that the jbrotli/brotli folder was empty (so I cloned the google repo to jbrotli/brotli

The build then started but failed on this:
jbrotli/jbrotli-native/src/main/cpp/de_bitkings_jbrotli_BrotliStreamCompressor.cxx:96:3: error: cast from pointer to smaller type 'int' loses information

Here's my install information:
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11", arch: "x86_64", family: "mac"

**Comment by nitram509** [comment]
Thank you for this feedback.
The reason is a conditional macro definition, which only works on Windows 64bit but not on OSX.
I plan to publish a fix during this weekend.

**Comment by nitram509** [comment]
@abradle 
I've committed a fix for this compiler issue.

There's another thing regarding the 'jbrotli/brotli' folder – this is a git submodule.
You can recognise such submodules, when there's a '.gitmodules' file within a git project.
In case of jbrotli, I link to brotli tagged with 'v0.2.0'.

One easy way to fetch submodules looks like this:

```
git submodule update --init --recursive
```

**Comment by abradle** [comment]
Great - thanks for the information and the fix!

Best wishes,

Anthony
