### ISSUE TITLE
New error on mvn package

### ISSUE THREAD

**Issue by abradle** [nitram509/jbrotli#2]
Hi,

Thanks for the [ERROR] /Users/anthony/Documents/jbrotli/jbrotli-native/darwin/src/test/java/de/bitkings/jbrotli/jni/LoadLibraryTest.java:[9,5] cannot find symbol
  symbol:   variable NativeLoader
  location: class de.bitkings.jbrotli.jni.LoadLibraryTest
[INFO] 1 error

I suspect this is missing?

ls on jbrotli/src/main/java/de/bitkings/jbrotli/ gives:
Brotli.java			BrotliError.java		BrotliStreamCompressor.java
BrotliCompressor.java		BrotliErrorChecker.java
BrotliDeCompressor.java		BrotliException.java

Let me know if you would like more info - thanks for your help on this!

Anthony

**Comment by nitram509** [comment]
Thank you for this feedback, this compiler issues I've solved.

Unfortunately on OSX the NativeLoader library I use, doesn't work.

For now, I recommend to use the following workaround for this issue.
run this in project root folder
```
mvn -pl jbrotli-native/darwin package to build the native lib
cp jbrotli-native/darwin/target/classes/libbrotli.dylib ./jbrotli
cp jbrotli-native/darwin/target/classes/libbrotli.dylib .
```

This will work for now.
Please keep in mind, that this is early experimental stage ;)

Regards
Martin

**Comment by abradle** [comment]
Great thankks! And thanks again for getting back so quick.

Yeah I get that - I'm happy to be a test monkey.

Thanks again!

Anthony

**Comment by nitram509** [comment]
Hi @abradle,

thank you for starring jbrotli on GitHub.
I'm the author of the project and want to let you know
that it has moved to another organisation.
https://github.com/meteogroup/jbrotli

Kind Regards and Merry Christmas
Martin
