### ISSUE TITLE
JRE crash using Brotli

### ISSUE THREAD

**Issue by abradle** [nitram509/jbrotli#3]
Hi again!

Thanks a lot for your help so far. We're now getting an issue where the JRE crashes.

The code below will trigger it reproducibly. If you only have one call to  "db.brotliBuild(100000)" it doesn't crash.

I hope this is enough information. Let me know if I'm doing something dumb! 

Anthony
```#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000103d111db, pid=881, tid=5891
#
# JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.66-b17 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x3111db]  jni_GetObjectClass+0x83
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/anthony/Documents/anthonytest/newtest/hs_err_pid881.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
````

```java

import java.io.IOException;
import org.scijava.nativelib.NativeLoader;

import de.bitkings.jbrotli.Brotli;
import de.bitkings.jbrotli.BrotliCompressor;

public class DebugBrotli {

	public void brotliBuild(int numChars) throws IOException{
		//
		BrotliCompressor compressor = new BrotliCompressor();
		StringBuilder bigData = new StringBuilder();
		for (int i=0; i<numChars;i++){
			bigData.append(i);
		}
		byte[] inBuf = bigData.toString().getBytes();
		System.out.println(inBuf.length);
		byte[] compressedBuf = new byte[2048];
		int outLength = compressor.compress(Brotli.DEFAULT_PARAMETER, inBuf, compressedBuf);
		System.out.println(outLength);
	}
	
	
	
	public static void main(String[] args) throws IOException{
		NativeLoader.loadLibrary("brotli");
		DebugBrotli db = new DebugBrotli();
		db.brotliBuild(100000);
		db.brotliBuild(100000);
	}
}
```

**Comment by nitram509** [comment]
Anthony,

the crash was not intended, of course ;-)
I made the output buffer length checking more robust - please pull newest sources.

That said, your sample code will no more crash the JVM but will fail with BrotliException:
```Error in native Brotli library 'COMPRESS_BrotliCompressBuffer' (Error code: -14)```

This is a bad description, I know, unfortunately the original brotli lib I'm wrapping doesn't provide more meaningful help. We may send this as feedback to original brotli developers, but my current focus is more on functional completeness, before I want to make it bright and shiny.

Thank you for being patient and providing feedback
:+1: 

Regards
Martin
