### ISSUE TITLE
Android NDK ARM support?

### ISSUE THREAD

**Issue by diegomontoya** [nitram509/jbrotli#4]
Frist, great job at getting JNI support for brotli for Java!

We are looking to integrate brotli but not sure what part of the build system needs to be changed to build armv7-a support using cpp compiler from Android NDK. 

Any pointers would be much appreciated.

**Comment by nitram509** [comment]
Hi, 

thank you for the flowers ;-)

Regarding Android support I think the current build system could be extended to produce
binaries for ARM CPUs. jbrotli uses Maven for the Java relevant code and cmake for the 
platform relevant code. 

I found [scripts](https://github.com/taka-no-me/android-cmake) to extend cmake to produce
build scripts which fit for the Android platform. 
To be honest I don't have any experience with the Android NDK, but I assume 
when you look at the jbrotli-native folder, you will get an idea how it could look like.

Of course, this requires the native brotli code to be compatible to Android platform.

Even if I currently don't plan to add Android support to jbrotli, I'm open to join forces.
If you have any ideas how jbrotli could be extended fork the code and I'm looking forward
to integrate pull requests.

I also plan to improve and automate the build pipeline, using http://concourse.ci/.
Such a pipeline would it make easier to produce binaries for different platforms
and upload them to e.g. Maven Central.

**Comment by nitram509** [comment]
Hi @diegomontoya,

thank you for starring jbrotli on GitHub.
I'm the author of the project and want to let you know
that it has moved to another organisation.
https://github.com/meteogroup/jbrotli

Kind Regards and Merry Christmas
Martin
